### ISSUE TITLE
Randomite gives creative items.

### ISSUE THREAD

**Issue by ProsperCraft** [kegare/Cavern2#1]
Randomite ore when broken has the ability to give you creative items that should not be in a survival world.

For example- a player got a Bibliocraft creative bookcase.

**Comment by kegare** [comment]
Yeah, it is normal.
But, I'll add a randomite blacklist config for you.

**Comment by MCJediYoda** [comment]
For Cavern 1 I created a mod called Cavern Tweaks to help control what is dropped from the Randomite Ores.  If it helps I can see about creating one for Cavern 2 unless Kegare can add a "whitelist" or "blacklist" feature for Randomite and Hybernate Items.

**Comment by kegare** [comment]
This enhancement was introduced on 2.0.3 build.

**Comment by ProsperCraft** [comment]
My modpack has so many items I had to add a mod that increased the forge limit, its proving a momumental task to add them all to the black list, can you please allow the config to toggle to become a whitelist?  Or disable randomite entirely?

**Comment by ProsperCraft** [comment]
@MCJediYoda It looks like we may need your mod, a player just got a creative capacitor.

**Comment by MCJediYoda** [comment]
OK I'll work on getting updated.

**Comment by MCJediYoda** [comment]
Just letting you know that I uploaded the new update to cavern tweaks 2.0
for Cavern II
This lets you add weighted specific items and quantity to the randomite ore
drops.
I did test on a few items and see it was working properly.
Not testing on every item so if you find any issues just let me know.

thanks

**Comment by ProsperCraft** [comment]
Is it on curse?

**Comment by MCJediYoda** [comment]
Should be soon waiting on approval

**Comment by ProsperCraft** [comment]
ok, I have tried to communicate with you in many other ways, but it's not getting a response.

@MCJediYoda Is there a version for Caverns 2 on curse? because the one you released 4 days ago crashes with caverns 2.

**Comment by MCJediYoda** [comment]
Version 2.0 is for Cavern II

**Comment by ProsperCraft** [comment]
@MCJediYoda check your bugtracker it crashes when you mine randomite.

**Comment by MCJediYoda** [comment]
I will check it thanks.
