### ISSUE TITLE
Advancements causing crashes when dimensions are disabled

### ISSUE THREAD

**Issue by Matryoshika** [kegare/Cavern2#15]
Minecraft: 1.12.2
Forge: 14.21.3.2669
Cavern II: v2.1.4

I've disabled a few of the dimensions by setting their id to 0, as specified in the configs that one should do, however, I get [this crash-report](https://gist.github.com/Matryoshika/f53bd8f49bf1cf8748a0ef2c9547719d) after doing so.

**Comment by kegare** [comment]
This issue is expired.
