### ISSUE TITLE
[1.12.2, Question] Portal sound

### ISSUE THREAD

**Issue by TheSnowyChickens** [kegare/Cavern2#16]
Hello,

I had to realize that your portal sound is load, very load and its only adjustable with the "Master Volume", so my settings are all in all very balanced, not to load but also not to silent and everytime I go through the portal I get a fright, because the volume of the portal. xD

Now my question: Can you change the source to "Ambient/Environment" or add an config option to disable it? 
I would very proud of you, if you can tweak there something. :D 

MC 1.12.2
Cavern2: Cavern_1.12.2-v2.1.5
Forge: 1.12.2 - 14.23.3.2678

**Comment by kegare** [comment]
This issue is expired
