### ISSUE TITLE
Randomite is too powerful

### ISSUE THREAD

**Issue by darkphan** [kegare/Cavern2#19]
Randomite would be much better if it only pulled from chest loot tables instead of any and every block in the game. Would it be possible to change randomite to this, or fix the blacklisting so we can just blacklist everyhing.

**Comment by ProsperCraft** [comment]
I have been asking for this since day 1

https://github.com/kegare/Cavern2/issues/6

Having to blacklist every single block in the game, then every new block that comes with mod updates is a major task and game-breaking if you don't get it right.

**Comment by kegare** [comment]
This issue is expired.
