### ISSUE TITLE
Cannot open Caveland or Ice Cavern portals

### ISSUE THREAD

**Issue by Astewen** [kegare/Cavern2#2]
I have opened the first 2 portals, but with Caveland I right-click with the sapling and nothing happens. For Ice Cavern it just places the packed ice block inside the frame. I tried adding triggerItems to the config files and use just a minecraft:iron_ingot but that does not work either. Could it be a mod conflict?

Mods:
[Pastebin](https://pastebin.com/Eh168eC6)

**Comment by kegare** [comment]
Caveland and Cavenia moved to mirage worlds.
Ice Cavern and Ruins Cavern were removed.

**Comment by kegare** [comment]
Please check here.
[https://minecraft.curseforge.com/projects/cavern2/pages/home](https://minecraft.curseforge.com/projects/cavern2/pages/home)
