### ISSUE TITLE
Crash Report Last Update v2.1.6

### ISSUE THREAD

**Issue by SheroxGG** [kegare/Cavern2#22]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (LootingModMC1.12.2-1.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.1.0-alpha-snapshot-universal.jar)
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  SSLoadingPlugin (Serene-Seasons-Mod-1.12.2.jar)
  NWRTweak (Redstone-Paste-Mod-1.12.1.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  llibrary (llibrary-core-1.0.4-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.176.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 5/22/18 12:55 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Cavern II (cavern)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/world/BlockEvent$PortalSpawnEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetPublicMethods(Class.java:2894)
	at java.lang.Class.getMethods(Class.java:1607)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81)
	at cavern.core.Cavern.preInit(Cavern.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.world.BlockEvent$PortalSpawnEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5506276240 bytes (5251 MB) / 8321499136 bytes (7936 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 Optifine OptiFine_1.12.2_HD_U_D2 117 mods loaded, 117 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                | Source                                             | Signature                                |
	|:----- |:--------------------- |:---------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2                 | minecraft.jar                                      | None                                     |
	| UCH   | mcp                   | 9.42                   | minecraft.jar                                      | None                                     |
	| UCH   | FML                   | 8.0.99.99              | forge-1.12.2-14.23.3.2655.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.23.3.2655           | forge-1.12.2-14.23.3.2655.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore         |                        | minecraft.jar                                      | None                                     |
	| UCH   | openmodscore          | 0.11.5                 | minecraft.jar                                      | None                                     |
	| UCH   | forgelin              | 1.6.0                  | Forgelin-1.6.0.jar                                 | None                                     |
	| UCH   | alib                  | 1.0.0                  | A-Lib-1.12.2.jar                                   | None                                     |
	| UCH   | orbis_api             | 1.12.2-1.1.2           | orbis_api-1.12.2-1.1.2.jar                         | None                                     |
	| UCH   | aether                | 1.12.2-1.0.5           | aether_ii-1.12.2-1.0.5.jar                         | None                                     |
	| UCH   | alchemistry           | 0.7.2                  | alchemistry-0.7.2.jar                              | None                                     |
	| UCH   | anvils                | 1.4.0.0                | Anvil-Enchantments-Mod-1.12.2.jar                  | None                                     |
	| UCH   | aquaculture           | 1.6.1                  | Aquaculture-Mod-1.12.2.jar                         | None                                     |
	| UCH   | arcademod             | 2.1.1                  | arcademod-2.1.1-1.12.2.jar                         | None                                     |
	| UCH   | architecturecraft     | @VERSION@              | ArchitectureCraft-Mod-1.12.2.jar                   | None                                     |
	| UCH   | armorchroma           | 1.3                    | Armor-Chroma-Mod-1.12.2.jar                        | None                                     |
	| UCH   | baubles               | 1.5.2                  | Baubles-Mod-1.12.2.jar                             | None                                     |
	| UCH   | astralsorcery         | 1.8.10                 | astralsorcery-1.12.2-1.8.10.jar                    | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCH   | codechickenlib        | 3.1.6.339              | CodeChickenLib-1.12.2.jar                          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | avaritia              | 3.2.0                  | Avaritia-1.12-3.2.0.13-universal.jar               | None                                     |
	| UCH   | battletowers          | 1.6.1                  | BattleTowers-Mod-1.12.2.jar                        | None                                     |
	| UCH   | bibliocraft           | 2.4.3                  | BiblioCraft-Mod-1.12.jar                           | None                                     |
	| UCH   | jei                   | 4.9.1.168              | jei_1.12.2-4.9.1.168.jar                           | None                                     |
	| UCH   | blockdrops            | 1.3.0                  | Block-Drops-Mod-1.12.jar                           | None                                     |
	| UCH   | thaumcraft            | 6.1.BETA12             | Thaumcraft-Mod-1.12.2.jar                          | None                                     |
	| UCH   | botania               | r1.10-354              | Botania+r1.10-354.jar                              | None                                     |
	| UCH   | buildcraftlib         | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| UCH   | buildcraftcore        | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| UCH   | buildcraftbuilders    | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| UCH   | buildcraftenergy      | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| UCH   | buildcraftfactory     | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| UCH   | buildcraftrobotics    | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| UCH   | buildcraftsilicon     | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| UCH   | buildcrafttransport   | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| UCE   | cavern                | 2.1.6                  | Cavern_1.12.2-v2.1.6.jar                           | None                                     |
	| UCH   | ctm                   | MC1.12-0.2.3.12        | CTM-MC1.12-0.2.3.12.jar                            | None                                     |
	| UCH   | chisel                | MC1.12.2-0.2.0.31      | Chisel-MC1.12.2-0.2.0.31.jar                       | None                                     |
	| UCH   | chococraft            | 0.9.1.52               | ChocoCraft-Mod-1.12.1.jar                          | None                                     |
	| UCH   | colorednametags       | 1.12.2-0.1.1           | Colored-Name-Tags-Mod-1.12.2.jar                   | None                                     |
	| UCH   | mantle                | 1.12-1.3.2.24          | Mantle-1.12-1.3.2.24.jar                           | None                                     |
	| UCH   | tconstruct            | 1.12.2-2.10.0.81       | TConstruct-1.12.2-2.10.0.81.jar                    | None                                     |
	| UCH   | conarm                | 0.0.17-b               | conarm-1.12.2-0.0.17-b.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | extendedrenderer      | v1.0                   | coroutil-1.12.1-1.2.10.jar                         | None                                     |
	| UCH   | coroutil              | 1.12.1-1.2.10          | coroutil-1.12.1-1.2.10.jar                         | None                                     |
	| UCH   | configmod             | v1.0                   | coroutil-1.12.1-1.2.10.jar                         | None                                     |
	| UCH   | cosmeticarmorreworked | 1.12.2-v1              | Cosmetic-Armor-Reworked-Mod-1.12.2.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCH   | cw                    | 1.0.2                  | creature_whisperer_1.0.2.jar                       | None                                     |
	| UCH   | cyclopscore           | 0.11.5                 | CyclopsCore-1.12.2-0.11.5.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | twilightforest        | 3.0.0                  | Twilight-Forest-Mod-1.12.2.jar                     | None                                     |
	| UCH   | deepmoblearning       | 1.12.2-1.2.0           | Deep-Mob-Learning-Mod-1.12.2.jar                   | None                                     |
	| UCH   | eleccore              | 1.8.434                | ElecCore-1.12.2-1.8.434.jar                        | None                                     |
	| UCH   | mcjtylib_ng           | 2.6.7                  | mcjtylib-1.12-2.6.7.jar                            | None                                     |
	| UCH   | elementaldimensions   | 0.2.0                  | elementaldimensions-1.12-0.2.0.jar                 | None                                     |
	| UCH   | enchdesc              | 1.1.8                  | Enchantment-Descriptions-Mod-1.12.2.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | evilcraft             | 0.10.36                | EvilCraft-Mod-1.12.1.jar                           | None                                     |
	| UCH   | evilcraftcompat       | 1.0.0                  | EvilCraft-Mod-1.12.1.jar                           | None                                     |
	| UCH   | extrautils2           | 1.0                    | Extra-Utilities-Mod-1.12.1.jar                     | None                                     |
	| UCH   | ic2                   | 2.8.16-ex112           | Industrial-Craft-2-Mod-Experimental-1.12.1.jar     | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | galacticraftcore      | 4.0.1.176              | GalacticraftCore-1.12.2-4.0.1.176.jar              | None                                     |
	| UCH   | galacticraftplanets   | 4.0.1.176              | Galacticraft-Planets-1.12.2-4.0.1.176.jar          | None                                     |
	| UCH   | mjrlegendslib         | 1.12.2-1.1.3           | MJRLegendsLib-1.12.2-1.1.3.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | extraplanets          | 1.12.2-0.3.6           | ExtraPlanets-1.12.2-0.3.6.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | forgivingvoid         | 1.0.17                 | ForgivingVoid_1.12.2-1.0.17.jar                    | None                                     |
	| UCH   | ichunutil             | 7.1.4                  | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
	| UCH   | nei                   | 2.4.1                  | Not-Enough-Items-1.12.2-Recommended.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | ftblib                | 5.0.2.14               | FTBLib-5.0.2.14.jar                                | None                                     |
	| UCH   | waila                 | 1.8.24                 | Hwyla-1.8.24-B39_1.12.jar                          | None                                     |
	| UCH   | llibrary              | 1.7.10                 | llibrary-1.7.10-1.12.2.jar                         | None                                     |
	| UCH   | iceandfire            | 1.3.1                  | Ice-and-Fire-Mod-1.12.2.jar                        | None                                     |
	| UCH   | hats                  | 7.0.0                  | iChuns-Hats-Mod-1.12.2.jar                         | None                                     |
	| UCH   | kjlib                 | 1.0.4                  | kjlib-1.0.4.jar                                    | None                                     |
	| UCH   | inventorygenerators   | 1.1.1                  | Inventory-Generators-Mod-1.12.2.jar                | None                                     |
	| UCH   | inventoryspam         | 1.0.2                  | Inventory-Spam-Mod-1.12.2.jar                      | None                                     |
	| UCH   | ironchest             | 1.12.2-7.0.40.824      | Iron-Chests-Mod-1.12.2.jar                         | None                                     |
	| UCH   | cjcm                  | 1.0                    | Jumping-Castle-Mod-1.12.2.jar                      | None                                     |
	| UCH   | mystic                | 0.7.0                  | Kether-Mod-1.12.2.jar                              | None                                     |
	| UCH   | keywizard             | 1.10.2-1.5             | keywizard-1.12.2-1.5.2.jar                         | None                                     |
	| UCH   | lootingmod            | 1.0                    | LootingModMC1.12.2-1.1.jar                         | None                                     |
	| UCH   | lucky                 | 7.5.0                  | Lucky-Block-Mod-1.12.zip                           | None                                     |
	| UCH   | radixcore             | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar               | None                                     |
	| UCH   | mca                   | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                     | None                                     |
	| UCH   | miniheads             | 1.0.7                  | Miniheads-Mod-1.12.2.jar                           | None                                     |
	| UCH   | mirror                | 1.12.2-0.1.0-0         | Mirror-Mod-1.12.2.jar                              | None                                     |
	| UCH   | mocreatures           | 12.0.3                 | Mo-Creatures-Mod-1.12.2.jar                        | None                                     |
	| UCH   | moartinkers           | 0.5.4                  | moartinkers-0.5.4.jar                              | None                                     |
	| UCH   | mob_grinding_utils    | 0.3.2                  | Mob-Grinding-Utils-Mod-1.12.jar                    | None                                     |
	| UCH   | moreplanets           | 2.0.14                 | More-Planets-1.12.2-2.0.14-GC156.jar               | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCH   | natura                | 1.12.2-4.3.2.49        | natura-1.12.2-4.3.2.49.jar                         | None                                     |
	| UCH   | recipehandler         | 0.9                    | No-More-Recipe-Conflict-Mod-1.12.1.jar             | None                                     |
	| UCH   | openmods              | 0.11.5                 | OpenModsLib-1.12.2-0.11.5.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | openblocks            | 1.7.6                  | OpenBlocks-1.12.2-1.7.6.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | planetprogression     | 1.12.2-0.2.3           | PlanetProgression-1.12.2-0.2.3.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | redstoneflux          | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar            | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | plustic               | 6.4.0.0                | plustic-6.4.0.0.jar                                | None                                     |
	| UCH   | redstonepaste         | 1.7.5                  | Redstone-Paste-Mod-1.12.1.jar                      | None                                     |
	| UCH   | schematics            | 1.12.2.3               | Schematics-1.12.2.3.jar                            | None                                     |
	| UCH   | sereneseasons         | 1.0.0                  | Serene-Seasons-Mod-1.12.2.jar                      | None                                     |
	| UCH   | silentlib             | 2.2.18                 | SilentLib-1.12-2.2.18-100.jar                      | None                                     |
	| UCH   | silentgems            | 2.6.9                  | SilentsGems-1.12-2.6.9b-265.jar                    | None                                     |
	| UCH   | sgextraparts          | 1.4.1                  | SGExtraParts-1.12-1.4.1-34.jar                     | None                                     |
	| UCH   | lteleporters          | 1.12.2-3.0.2           | Simple-Teleporters-Mod-1.12.2.jar                  | None                                     |
	| UCH   | squeedometer          | 1.0.4                  | Squeedometer-mc1.12.x-1.0.4.jar                    | None                                     |
	| UCH   | thaumicjei            | 1.2.1                  | Thaumic-JEI-Mod-1.12.2.jar                         | None                                     |
	| UCH   | thebetweenlands       | 3.1.0-alpha-snapshot   | TheBetweenlands-3.1.0-alpha-snapshot-universal.jar | None                                     |
	| UCH   | tinker_io             | release 2.5.5e         | tinker_io-1.12-release 2.5.5e.jar                  | None                                     |
	| UCH   | tinkersjei            | 1.0                    | Tinkers-JEI-Mod-1.12.2.jar                         | None                                     |
	| UCH   | tinkertoolleveling    | 1.12-1.0.3.DEV.56fac4f | Tinkers-Tool-Leveling-Mod-1.12.2.jar               | None                                     |
	| UCH   | toroquest             | 1.12.2-5.2             | ToroQuest-Mod-1.12.2.jar                           | None                                     |
	| UCH   | totemic               | 1.12.2-0.9.0           | Totemic-Mod-1.12.2.jar                             | None                                     |
	| UCH   | tropicraft            | 7.1.0.50               | Tropicraft-Mod-1.12.2.jar                          | None                                     |
	| UCH   | ultimate_unicorn_mod  | 1.5.14                 | Ultimate-Unicorn-Mod-1.12.2.jar                    | None                                     |
	| UCH   | unlimitedchiselworks  | 0.1.11                 | UnlimitedChiselWorks-0.1.11.jar                    | None                                     |
	| UCH   | wailaharvestability   | 1.1.11                 | Waila-Harvestability-Mod-1.12.jar                  | None                                     |
	| UCH   | weather2              | 1.12.1-2.6.10          | weather2-1.12.1-2.6.10 (1).jar                     | None                                     |
	| UCH   | xaerominimap          | 1.15.1                 | Xaeros_Minimap_1.15.1_Forge_1.12.jar               | None                                     |
	| UCH   | yabba                 | 1.1.2.7                | YABBA-1.1.2.7.jar                                  | None                                     |
	| UCH   | corail_pillar         | 4.1.0                  | corail_pillar-4.1.0-1.12.jar                       | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (LootingModMC1.12.2-1.1.jar)
  com.ToMe.LootingMod.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.1.0-alpha-snapshot-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  
SSLoadingPlugin (Serene-Seasons-Mod-1.12.2.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
NWRTweak (Redstone-Paste-Mod-1.12.1.jar)
  net.fybertech.nwr.NWRTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
llibrary (llibrary-core-1.0.4-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.176.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_D2
	OptiFine Build: 20180430-132249
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 397.64
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by kegare** [comment]
You need to update your Forge.
Requires Forge 14.23.3.2697 and newer.
