### ISSUE TITLE
Stuck in cavern dimension

### ISSUE THREAD

**Issue by localzuk** [kegare/Cavern2#23]
I'm playing the pack "Towncraft", which includes this mod. I seem to now be stuck in the cavern dimension though (the one you get to with mossy cobble and gravel to make the portal).

Whenever I go into the portal, it goes black like I'm being transported to the overworld, then it just leaves me in the portal still.

I've tried demolishing the portal and rebuilding in place, and moving it a distance away, with the same result. I tried restarting the game also.

I used Journeymap to teleport back, and then tried the portal again it all worked fine. If there is anything that I can do to provide more diagnostics, please let me know.

**Comment by localzuk** [comment]
OK. After playing for a couple more hours, this has happened in the Huge Cavern dimension now too. One thing I did notice is that all the hostile mobs become invisible. They're still there, and still attack, you just can't see them.

**Comment by Reassembly** [comment]
I had the same problem, but not with the "Towncraft" pack. Like you, I couldn't leave the cavern without teleporting out (I had a tablet from Corail Tombstone), and after teleporting out, the portal seemed to work properly in both directions again.

The mods I have in common with Towncraft are Corail Tombstone, FoamFix, and VanillaFix. If there's a mod incompatibility issue, and not a stand-alone problem, it's probably with one of those three mods.

**Comment by jkissinger** [comment]
Just ran into this as well, seems like the mod is teleporting you to the next dimension it expects you to be in.  In other words if the portal last teleported you to the overworld, next time it teleports you to the cavern dimension.  But if you teleport any other way, it gets stuck teleporting you to the same dimension you're in.

**Comment by Flimsy-Fox** [comment]
I have these exact same problems as well!

**Comment by jaz000** [comment]
We found there to be a log of lag when going through portals. It felt like the world was loading too slow and by the time it had the portal had sent you back. Sometimes trying to move out of the portal before the world had loaded helped.

there is an option in general.cgf:
      B:portalCache=true
Setting this to true might help, wo don't have the problem so much now, but other performance tweaks might also be helping ..

**Comment by lividraffy** [comment]
I tried this, didn't help. I'm not the server administrator, I'm just looking for a solution for him to try. I don't know what changing that code actually does but after we did that the overworld actually loaded before it booted me back to the cavern dimension. Any other tips for how to fix this annoying bug would be greatly appreciated.

**Comment by kegare** [comment]
This issue is expired.
