### ISSUE TITLE
Crash on oredict handling 

### ISSUE THREAD

**Issue by BloodWorkXGaming** [kegare/Cavern2#25]
This line crashes with index out bounds if the oredict is only the prefix, with nothing else.

https://github.com/kegare/Cavern2/blob/2578ff455aa56cf0be94b835c4f1401ca563db8d/cavern/block/RandomiteHelper.java#L45

**Comment by stevojhall** [comment]
i am getting this crash too when adding to enigmatica 2 expert

https://pastebin.com/95pG0sd8

**Comment by kegare** [comment]
This issue was fixed.
