### ISSUE TITLE
Miner Rank Requirements

### ISSUE THREAD

**Issue by Shattered2909** [kegare/Cavern2#27]
So I am using your mod in my pack for exploration dims, but I want to disable the entire mining assist/miner rank system. Is there a way? If no, can you add one? I dislike the dimension restriction and it is conflicting with my pack.

**Comment by O13SC3N3** [comment]
I would also like this feature, It throws off the entire theme and aspect of my modpack as well. I do enjoy the dimensions and would love to utilize them.

**Comment by kegare** [comment]
This issue is expired.
