### ISSUE TITLE
traditional chinese zh_TW.lang file

### ISSUE THREAD

**Issue by ckhomo** [kegare/Cavern2#28]
Dear developer.

I made a traditional chinese translate version of this mod . Since I cannot pull a request(dunno why) , I decide to post my file here.
[zh_TW.lang.txt](https://github.com/kegare/Cavern2/files/2201729/zh_TW.lang.txt)

modに対するいつもの開発やメンテナンス、心から深く御礼申し上げます。

**Comment by kegare** [comment]
This issue is expired.
