### ISSUE TITLE
Slow mining when activating "mining assist" in Towncraft modpack

### ISSUE THREAD

**Issue by funfox1** [kegare/Cavern2#29]
Hello !

I'm curently trying the Towncraft modpack, that uses Cavern2 on 1.12.2.

As soon as i started using picks higher than stonepicks, i started to see that if i activate mining assist (any of them, ranged / quick / adit, my mining speed gets SLOOOOOOOW. like 3-5 sec per block of stone slow.
This disapear if i turn mining assist to disabled.

I discovered that when i turn the mining-assist.cfg option B:modifiedHardness to false, the speed gets back to normal. Still, i don't think that the hardness for stone breaking should be that high... else it destroys the bonus of mining assist !

Is it a problem with the hardness for stone? i'm using an iron pickaxe, with a magnite miner lvl.

EDIT : i discovered the problem to be only on "ranged" and "adit", not on "quick". I saw a vid since that explains the speed to be tied to the number of blocks destroyed. SO not a bug finally, you can close the ticket. (still, a bit of explaination somewhere of what "quick, ranged and adit" do on your wiki would be nice, i couldn't find it)

**Comment by ProsperCraft** [comment]
It is a bug, because it happens on single player, but not on a server.

**Comment by kegare** [comment]
It is normal.
