### ISSUE TITLE
customize which biomes spawn in the caverns

### ISSUE THREAD

**Issue by MCJediYoda** [kegare/Cavern2#3]
I am checking out Cavern 2 v2.0.2.  How can I customize which Biomes spawn in the Cavern dimensions?
I was exploring the Caveland dimension and found Abyssalcraft Darklands Mountain biome.  I would like to have a few biomes from BiomesOPlenty and limit the AquaCavern to Oceans/DeepOceans.  Changing cavern-biomes.cfg doesn't seem to affect what biomes can spawn.  maybe a whitelist/blacklist for biomes?

**Comment by kegare** [comment]
If you change the biome type to square, only customized biomes will allow to generate in the dimension.
But, natural type cannot do it, and I will eventually improve this.

**Comment by MCJediYoda** [comment]
ah thanks.  I'll give this a try.
