### ISSUE TITLE
Portals on servers are too fast now, players can't get out in time.

### ISSUE THREAD

**Issue by ProsperCraft** [kegare/Cavern2#31]
After the last update, portals are now too fast on servers, and players can't get out before instantly sent back to where they came from.  This leaves them stuck in the current dim.

**Comment by ProsperCraft** [comment]
Here is a video a player made.
https://www.dropbox.com/s/mjbbqkczhnkm1yq/TownCraft_Issue.mp4?dl=1

**Comment by DerpTheBugbear** [comment]
Same issue, stuck in infinite loop between portals.  Mod is unplayable.

**Comment by ProsperCraft** [comment]
We worked around it in TownCraft by adding the mod that lets players dig up and touch bedrock to get out, and vice versa, but it is a hack, and we will get tons of complaints from players about the non working portals.

**Comment by kegare** [comment]
This issue was fixed
