### ISSUE TITLE
Caverns portals link to themseleves.

### ISSUE THREAD

**Issue by ProsperCraft** [kegare/Cavern2#32]
I keep having players get stuck not being able to use their portal in the cavern to return to the overworld, it flashes as if you are teleporting, then you end up back in the same portal facing the other way.

And oddly enough it seems to spawn a baby zombie holding gravel, or a caverns zombie holding a spruce door in the overworld?? I don't know its just odd.

Anyhow please check the teleport code against the latest forge.

**Comment by ProsperCraft** [comment]
This is still a major problem where people enter the portal and get teleported right back where they started trapping them.

**Comment by ProsperCraft** [comment]
https://github.com/kegare/Cavern2/issues/23

**Comment by kegare** [comment]
This issue was fixed.
