### ISSUE TITLE
Mobs invisible after going between dimensions

### ISSUE THREAD

**Issue by NetGlitched** [kegare/Cavern2#33]
If I enter or exit the cavern (I've only entered the normal basic cavern so far) mobs become invisible (I think it only affects mobs that had already spawned) and I don't know how to fix this, if it's even in my control to begin with. The mod is amazing and I still want to use it, but is there any way to fix this? If not, will any updates be coming out at some point to fix this?

**Comment by SynexWolf** [comment]
I believe this isn't due to cavern, I think it's related to a weird conflict error between CodeChicken Lib and iChunUtil. Try removing one of them and see if you still get the issue.

**Comment by kegare** [comment]
This issue is expired
