### ISSUE TITLE
Config Features

### ISSUE THREAD

**Issue by jelaw21** [kegare/Cavern2#34]
I was wondering if you wouldn't mind adding a few config options. 

1. Remove water breathing in the Aqua Cavern
2. Remove mining dimension mining level requirements. 

I am making a pack centered around surviving the environment, but if Aqua miner gives you water breathing and fast mining under-water and you have to reach Aqua level to enter the dim, there is no real challenge to the dimension, like the others have with the Cavenic and Crazy Mobs.

Thanks,

**Comment by kegare** [comment]
This issue is expired
