### ISSUE TITLE
Mining Rank/Points not displayed

### ISSUE THREAD

**Issue by Jaseac** [kegare/Cavern2#39]
Nothing displayed on screen no matter where you chose to have it displayed. So you have no idea if your getting xp nor how close you are to the next level up.

**Comment by k1xy** [comment]
same issue!

**Comment by k1xy** [comment]
[https://github.com/kegare/Cavern2/issues/36#issuecomment-615736907](url)

fixed! everything works1

**Comment by fkrisi11** [comment]
@k1xy How did you fix it? I can't find anything when clicking that link.

**Comment by kegare** [comment]
This issue is expired.
