### ISSUE TITLE
[1.12] All Players get timeouted, while 1 player mines in the cave dimension

### ISSUE THREAD

**Issue by MasterEnderman** [kegare/Cavern2#4]
After the timeout of all players the console constantly spams this message: https://pastebin.com/Rq8aMzEn

Cavern2: 2.0.5
Forge: 14.23.1.2606

**Comment by ProsperCraft** [comment]
If you update forge and caverns does it still happen? We don't have this issue on a large multiplayer server (TownCraft modpack)

**Comment by MasterEnderman** [comment]
Couldn't reproduce it since the update. Closing this issue for now.
