### ISSUE TITLE
Crash connected to Bewitchment

### ISSUE THREAD

**Issue by happybandit360** [kegare/Cavern2#46]
Any time anyone encounters a Cavenic or Crazy Skeleton (regardless of dimension) as soon as it attempts to attack, the game (and server) crashes. If playing on Creative, there is no issues because the skeletons are not attempting to attack. 

All potentially helpful version information
Minecraft 1.12.2
Forge 14.23.5.2838
Caverns II 1.12.2-v2.2.0
Bewitchment 1.12.2-0.0.20.8

Crash Report: https://paste.ee/p/1MkwI

This issue also has been reported to the Bewitchment dev.

**Comment by JoelZBub** [comment]
#https://github.com/Um-Mitternacht/Bewitchment/issues/438

**Comment by kegare** [comment]
This issue is expired.

**Comment by JoelZBub** [comment]
Sorry, this was a Bewitchment issue, and we gave up on trying to use that mod because it's a buggy junkpile.
