### ISSUE TITLE
Odd unexplained problems with mining assist

### ISSUE THREAD

**Issue by kotoroshinoto** [kegare/Cavern2#47]
it was working, and suddenly it stopped working.

For a while Nothing I broke in cavern dimensions dropped any items at all.

I don't know if this is some kind of penalty for using mining assist, or if something is bugged.

**Comment by kotoroshinoto** [comment]
items are dropping now, but mining assist isn't doing anything at all

**Comment by kegare** [comment]
This issue is expired.
