### ISSUE TITLE
About the ore dictionary

### ISSUE THREAD

**Issue by ckhomo** [kegare/Cavern2#5]
Dear developer , 
This mod is big but also have high compatibility with other major mods generating ores.
Today I found that the item IDs in the mod doesn't match with others I saw in game.

I think a link of a picture can explain this well.
https://imgur.com/ffdXUbn
Currently it does not cause any bugs so far , and I am not familiar with Java.
but by improving this I think it can raise the compatibility.(able to let other mods use your ore/ingot to smelt/craft etc.)For more details I think you can find something by Google "forge oredict".

modのご開発、心から厚く感謝いたします。
これからの健闘を祈り申し上げます。

**Comment by kegare** [comment]
It has nothing to do with ore dictionary.
