### ISSUE TITLE
Please have an option for whitelist

### ISSUE THREAD

**Issue by ProsperCraft** [kegare/Cavern2#6]
I have 14,000 lines of blacklist, and items that are blacklisted are still dropping on occasion because of the way the mod authors program things, like Forestry and Thermal Expansion.

Please let us configure a whtelist instead.

**Comment by ProsperCraft** [comment]
Please, this mod is going to ruin servers, even with blacklisting so many items a player got a creative capacitor.

![creativecapacitor](https://user-images.githubusercontent.com/4427684/37420174-cddd6454-277b-11e8-90ea-b90b8cf33cea.png)

Here is my 500k filesize blacklist- 
[general.zip](https://github.com/kegare/Cavern2/files/1812283/general.zip)

**Comment by ProsperCraft** [comment]
https://github.com/CoFH/Feedback/issues/926#issuecomment-373118551

**Comment by KingLemming** [comment]
To be fair, whereas you are calling out TE specifically...I checked your file, you just straight up aren't blacklisting the metadata entry for Creative, which is 32000.

Having said that - yes, whitelist is *absolutely* the way to go here and this is a very common sense request.

**Comment by ProsperCraft** [comment]
I am begging you, please add a whitelist so we can do away with the blacklist, it is monumental to maintain, and players keep getting items that they are not supposed to have, some of which cause crashes.

**Comment by kegare** [comment]
This issue is expired.
