### ISSUE TITLE
Server Crash - 2.1.0 Client side code on the server?

### ISSUE THREAD

**Issue by ProsperCraft** [kegare/Cavern2#7]
https://paste.fedoraproject.org/paste/q70kDOpMSzdxmpk7I3kaTw

**Comment by ProsperCraft** [comment]
Another one with updated forge - https://paste.fedoraproject.org/paste/8LaaHt3mfUHyfN0DDrCC6A

**Comment by An-Sar** [comment]
i ran into this as well, not to pile on =D, but i recreated the crash with only Cavern II and forge-1.12.2-14.23.2.2611 

https://pastebin.com/4rPhdTF7

thank you for the great work

**Comment by kegare** [comment]
This issue fixed on version 2.1.1.
